### ISSUE TITLE
Incorrect Link to Currencies in Plugins Menu

### ISSUE THREAD

**Issue by jkomar** [nekojira/wp-currencies#1]
After the plugin is activated, if you click on the 'Currencies' link under the plugin name on the installed plugins page, the link is incorrect and results in a WordPress error, "You do not have sufficient permissions to access this page."

The link ends in, "?page=wp-currencies". The - (hyphen) in wp-currencies should be an _ (underscore). The 'Currencies' link in the Settings menu is fine.

Jason

**Comment by unfulvio** [comment]
I think latest commit fixed this, thanks for pointing out the issue
