### ISSUE TITLE
How do I use this in my Javascript/Jquery?

### ISSUE THREAD

**Issue by NilsDannemann** [nekojira/wp-currencies#10]
Sorry, but I just don't get it. 

The Plugin works great, but how do I access is in my JS/JQuery code?

```javascript
jQuery(document).ready( function() {
	var total = 1000;
	// Obviously this isn't working, but how would I achieve something like this?
	var totalConverted = convert_currency( $amount = total, $from = 'USD', $in = 'EUR' );

	console.log(totalConverted);
});
```

**Comment by unfulvio** [comment]
hey @NilsDannemann thanks for using the plugin -- I haven't really followed development in a while but looks stable

WP Currencies adds an ajax action that you can query to return rates https://github.com/unfulvio/wp-currencies/blob/878565e22c9f4115c91be083fb5afae5d437c268/includes/functions.php#L53-L67

you need to perform an ajax call to `get_exchange_rates` - it should work as any other ajax request using jQuery in a WordPress context: https://codex.wordpress.org/AJAX_in_Plugins (check also tutorials and resources at the bottom)
