### ISSUE TITLE
Can't make the get_exchange_rates_json work

### ISSUE THREAD

**Issue by dbeja** [nekojira/wp-currencies#11]
Hi,

I tried to use the ajax function get_exchange_rates_json but couldn't make it work because the currency parameter is being read from the function argument instead of the $_GET.
I changed the code to read the argument from $_GET['currency'] so that it works.

Is there any way to use this function in javascript?

Should I do a pull request of this change?

Thanks

**Comment by unfulvio** [comment]
hey @dbeja thanks for using the plugin (I haven't used it or followed development in a while, but looks stable...)

I think the rationale there was to always have the USD $ as base currency in ajax; once you have all the currency rates with the USD base, you can easily perform conversions within your own JS script logic

or you could create a new ajax action and use the public `get_exchange_rates_json()` function within your own callback
