### ISSUE TITLE
php 7.1 error

### ISSUE THREAD

**Issue by maxi-millian** [nekojira/wp-currencies#12]
Fatal error: Uncaught Error: [] operator not supported for strings in /home/maxrom/agroonetest.info/www/wp-content/plugins/wp-currencies/includes/functions.php:258 Stack trace: #0 /home/maxrom/agroonetest.info/www/wp-content/plugins/wp-currencies/includes/functions.php(90): currency_exists('USD') #1 /home/maxrom/agroonetest.info/www/wp-content/plugins/wp-currencies/includes/extensions/shortcodes.php(54): convert_currency(3600, 'USD', 'UAH') #2 /home/maxrom/agroonetest.info/www/wp-includes/shortcodes.php(345): WP_Currencies\Shortcodes->currency_conversion_shortcode(Array, '', 'currency_conver...') #3 [internal function]: do_shortcode_tag(Array) #4 /home/maxrom/agroonetest.info/www/wp-includes/shortcodes.php(223): preg_replace_callback('/\\[(\\[?)(post_v...', 'do_shortcode_ta...', '<!--\n&#91;cred_...') #5 /home/maxrom/agroonetest.info/www/wp-includes/class-wp-hook.php(298): do_shortcode('<!--\n&#91;cred_...') #6 /home/maxrom/agroonetest.info/www/wp-includes/plugin.php(203): WP_Hook->apply_filters('<!--\n[cred_link...', Arr in /home/maxrom/agroonetest.info/www/wp-content/plugins/wp-currencies/includes/functions.php on line 258

**Comment by unfulvio** [comment]
thanks @maxi-millian should have fixed in https://github.com/unfulvio/wp-currencies/commit/2ded9e3b59865d5ed178281b5da27b6ea089fb6a

plan to release in wordpress.org repository later this week v 1.4.7

sorry for the delay, I'm not actively maintaining this plugin

**Comment by maxi-millian** [comment]
Fulvio, thank you very much
