### ISSUE TITLE
Acf v5.x (acf_force_type_array)

### ISSUE THREAD

**Issue by Liabfi** [nekojira/wp-currencies#7]
Hello, there is an issue with acf and wp_currencies with this function : 

```
acf_force_type_array
```

This function don't exist anymore in the last version of Acf

**Comment by unfulvio** [comment]
ok, unfortunately v5.x is not on a public repo so I can't quickly check at the moment
is there a depreciation note somewhere or a substitute function?
ACF support in WP Currencies was built upon the template Elliot provided, perhaps you can also issue a pull request if you have a fix

**Comment by unfulvio** [comment]
ok  from what I read here, the function is just an helper

https://github.com/elliotcondon/acf/blob/4253a316415237fe73eefde11cd54199285ece26/core/api.php#L1499

I will implement my own method to achieve the same thing and update

**Comment by unfulvio** [comment]
ok, can you download a zip from the master branch here and check if it's ok now? should have been fixed

**Comment by Liabfi** [comment]
It works for me !
