### ISSUE TITLE
Correctly format for Brazilian Real

### ISSUE THREAD

**Issue by AndreCapelache** [nekojira/wp-currencies#8]
Can you change the format from Brazilian Real?

The correct format for Brazilian Real is:
https://pt.wikipedia.org/wiki/Real_(moeda)

// Brazilian Real
                $data[$currency_code] = array(
                    'name'          => $currency_data['name'],
                    'symbol'        => 'R&#36;',
                    'position'      => 'before',
                    'decimals'      => 2,
                    'thousands_sep' => '.',
                    'decimals_sep'  => ',',
                );

**Comment by unfulvio** [comment]
done in the last commit on master branch, feel free to issue pull requests for this or other incomplete or wrong currency formatting params, thanks

**Comment by AndreCapelache** [comment]
Thank you for the kindness of include the correctly format for Real currency in your great WordPress plugin!

**Comment by unfulvio** [comment]
you are welcome - obrigado
if you like the plugin you can also star it or vote/review it on WordPress
https://wordpress.org/plugins/wp-currencies/
