### ISSUE TITLE
problem fetching currency data

### ISSUE THREAD

**Issue by james182** [nekojira/wp-currencies#9]
I have a valid API Key but when i use this <?php echo convert_currency( '1', 'USD', 'AUD' ); ?> i get the erroe below: 

Warning: WP Currencies: There was a problem fetching currency data from database. Is your API key valid? in /html/wp-content/plugins/wp-currencies-master/includes/functions.php on line 117

I have de-activated and deleted and then re-installed the latest version but the error still remains.

**Comment by unfulvio** [comment]
Hi,
1. does the error happen only when using that particular function? 
2. make sure the site running the plugin can reach openexchangerates.org api
3. check if currencies were stored in database (see wp_currencies table)

**Comment by harin** [comment]
Experiencing the same issue here.
1. Tried get_exchange_rates() in addition and got error about no rates data.
2. Tried curling the server and it works, so the server have access to openexchangerates.org, not sure if this translates to the plugin can reach the website.
3. The database is empty, on table created but no data.

WP - 4.3.1
php - 5.5.9
 mysql - 5.5.43

**Comment by Ogien** [comment]
What I have done that works, is deleting the API key from the account.
Making a new API key.
Delete the API Key that in WordPress then save. After the field is cleared & saved, add the new API Key in.

That should solve the DB Empty issue.

Here is the code I am using to solve the issue of creating a Auto-currency exchange.

``` php
function wcml_auto_update_exchange_rates( $rates_array ) {
    // Base Currency is USD, it can be anything
    foreach ($rates_array as $key => $value) {
      $rates_array[$key] = get_exchange_rate("USD", $key);
    }

    return $rates_array;
}
add_filter( 'wcml_exchange_rates', 'wcml_auto_update_exchange_rates');
```
